version: "3.3"

services:
  montagu:
    build: .
    image: sopelirc/sopel:latest
    environment:
      - PUID=1004
      - PGID=1004
    volumes:
      - /home/chat/montagu/sopelconf:/home/sopel/.sopel/